// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8ZdPPwZQz7-l-5HTyS_ePntS4u7OS68',
    appId: '1:658008688279:web:0f9e3bc91a0efe598dcbd2',
    messagingSenderId: '658008688279',
    projectId: 'notes-app-14c72',
    authDomain: 'notes-app-14c72.firebaseapp.com',
    storageBucket: 'notes-app-14c72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIPClcZvWqwjVMb8t3fMh1sP_JPIzKQw',
    appId: '1:658008688279:android:62a6cde9c0eab5c48dcbd2',
    messagingSenderId: '658008688279',
    projectId: 'notes-app-14c72',
    storageBucket: 'notes-app-14c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcPuivzPl1Z06kfpf4Fmt24inrZ6mUBFQ',
    appId: '1:658008688279:ios:35be1f693be3edd88dcbd2',
    messagingSenderId: '658008688279',
    projectId: 'notes-app-14c72',
    storageBucket: 'notes-app-14c72.appspot.com',
    iosClientId: '658008688279-2qhf4p2c8p5ic6hleetpfjgvjgkq2orn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcPuivzPl1Z06kfpf4Fmt24inrZ6mUBFQ',
    appId: '1:658008688279:ios:35be1f693be3edd88dcbd2',
    messagingSenderId: '658008688279',
    projectId: 'notes-app-14c72',
    storageBucket: 'notes-app-14c72.appspot.com',
    iosClientId: '658008688279-2qhf4p2c8p5ic6hleetpfjgvjgkq2orn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDdd',
  );
}
